import * as fs from 'node:fs';
import * as path from 'node:path';

export interface ReportParams {
  targetUrl: string;
  auditDir: string;
  sessionId: string;
  agentResults: Record<string, AgentResultSummary>;
  phaseResults: Record<string, string>;
}

export interface AgentResultSummary {
  category: string;
  analysisFile: string;
  exploitFile: string;
  deliverables: string[];
  turnCount: number;
  durationMs: number;
  error?: string;
}

export async function assembleReport(params: ReportParams): Promise<string> {
  const { targetUrl, auditDir, sessionId, agentResults, phaseResults } = params;
  const reportPath = path.join(auditDir, 'final-report.md');

  const lines: string[] = [];
  lines.push('# Shannon Security Assessment Report');
  lines.push('');
  lines.push(`**Target:** ${targetUrl}`);
  lines.push(`**Session:** ${sessionId}`);
  lines.push(`**Date:** ${new Date().toISOString()}`);
  lines.push('');
  lines.push('## Executive Summary');
  lines.push('');
  lines.push('This report contains the results of an autonomous white-box penetration test.');
  lines.push('All findings include proof-of-concept exploits that were verified against the live application.');
  lines.push('');

  // Phase results section
  lines.push('## Pre-Reconnaissance Results');
  lines.push('');
  for (const [key, resultPath] of Object.entries(phaseResults)) {
    if (key.startsWith('pre-recon-') && fs.existsSync(resultPath)) {
      const content = fs.readFileSync(resultPath, 'utf-8').slice(0, 2000);
      lines.push(`### ${key.replace('pre-recon-', '')}`);
      lines.push(`\`\`\`\n${content}\n\`\`\``);
      lines.push('');
    }
  }

  lines.push('## Reconnaissance Results');
  lines.push('');
  for (const [key, resultPath] of Object.entries(phaseResults)) {
    if (key.startsWith('recon-') && fs.existsSync(resultPath)) {
      const content = fs.readFileSync(resultPath, 'utf-8').slice(0, 2000);
      lines.push(`### ${key.replace('recon-', '')}`);
      lines.push(`\`\`\`\n${content}\n\`\`\``);
      lines.push('');
    }
  }

  // Agent results section
  lines.push('## Vulnerability Analysis & Exploitation');
  lines.push('');
  for (const [agentType, result] of Object.entries(agentResults)) {
    lines.push(`### ${agentType}`);
    lines.push('');
    lines.push(`- **Category:** ${result.category}`);
    lines.push(`- **Turns:** ${result.turnCount}`);
    lines.push(`- **Duration:** ${(result.durationMs / 1000).toFixed(1)}s`);
    if (result.error) {
      lines.push(`- **Error:** ${result.error}`);
    }
    lines.push('');

    if (result.analysisFile && fs.existsSync(result.analysisFile)) {
      const content = fs.readFileSync(result.analysisFile, 'utf-8').slice(0, 5000);
      lines.push('#### Analysis');
      lines.push(`\`\`\`\n${content}\n\`\`\``);
      lines.push('');
    }

    if (result.exploitFile && fs.existsSync(result.exploitFile)) {
      const content = fs.readFileSync(result.exploitFile, 'utf-8').slice(0, 5000);
      lines.push('#### Proof-of-Concept Exploit');
      lines.push(`\`\`\`\n${content}\n\`\`\``);
      lines.push('');
    }
  }

  lines.push('## Metrics');
  lines.push('');
  const totalTurns = Object.values(agentResults).reduce((s, r) => s + r.turnCount, 0);
  const totalDuration = Object.values(agentResults).reduce((s, r) => s + r.durationMs, 0);
  lines.push(`- **Total Agent Turns:** ${totalTurns}`);
  lines.push(`- **Total Duration:** ${(totalDuration / 1000).toFixed(1)}s`);
  lines.push('');
  lines.push('---');
  lines.push('*Report generated by Shannon Autonomous Pentesting Framework*');

  const content = lines.join('\n');
  fs.writeFileSync(reportPath, content);
  return reportPath;
}
